### ISSUE TITLE
Adjustable overdrive projector error

### ISSUE THREAD

**Issue by joejoe0243** [abomb4/super-cheat#16]
When I build the projector, game crashed.

`rhino.EcmaError: TypeError: Cannot call property efficiency in object Building#2896334[23,60]:invincible-cheat-mod-v7-adjustable-overdrive-projector. It is not a function, it is "number". (adjustable-overdrive-projector#115)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3741)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3721)
	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3750)
	at rhino.ScriptRuntime.typeError3(ScriptRuntime.java:3772)
	at rhino.ScriptRuntime.notFunctionError(ScriptRuntime.java:3832)
	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2192)
	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2175)
	at rhino.optimizer.OptRuntime.callProp0(OptRuntime.java:69)
	at rhino.gen.adjustable_overdrive_projector_20._c_anonymous_28(adjustable-overdrive-projector:115)
	at rhino.gen.adjustable_overdrive_projector_20.call(adjustable-overdrive-projector)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.adjustable_overdrive_projector_20.call(adjustable-overdrive-projector)
	at rhino.Context.lambda$call$0(Context.java:441)
	at rhino.Context.call(Context.java:450)
	at rhino.Context.call(Context.java:441)
	at rhino.JavaAdapter.callMethod(JavaAdapter.java:466)
	at adapter42.drawLight(<adapter>)
	at mindustry.graphics.BlockRenderer.drawBlocks(BlockRenderer.java:467)
	at mindustry.core.Renderer.draw(Renderer.java:368)
	at mindustry.core.Renderer.update(Renderer.java:224)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:230)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)`

**Comment by Ptnecni** [comment]
same here, Adjustable Overdrive Projector crashes the game when it's built, and as soon as I try to go back to that world (The Craters), the game crashes instantly

**Comment by abomb4** [comment]
Fixed in 3.1.1
